# Generated by Django 4.0.4 on 2022-05-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='Mains',
        ),
    ]
