# Generated by Django 4.0.4 on 2022-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_course_str_attended_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_username', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=100)),
                ('s_username', models.CharField(max_length=100)),
                ('s_email', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('join_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Non_approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_username', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=100)),
                ('s_username', models.CharField(max_length=100)),
                ('s_email', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('join_code', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='course_str',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='course_str',
            name='attended_students',
        ),
        migrations.RemoveField(
            model_name='course_str',
            name='total_registered_students',
        ),
        migrations.AddField(
            model_name='course_str',
            name='attended_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='attended_list',
            field=models.TextField(null=True),
        ),
    ]
