# Generated by Django 4.0.4 on 2022-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_approved_s_id_non_approved_s_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_attendace_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_username', models.CharField(max_length=100)),
                ('s_username', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('date', models.DateField(default='2021-10-10')),
                ('bool', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterModelOptions(
            name='live',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='live',
            name='date',
            field=models.DateField(default='2021-10-10'),
        ),
    ]
