# Generated by Django 4.0.4 on 2022-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_course_str_time_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='time_present',
            field=models.IntegerField(default=0),
        ),
    ]
