# Generated by Django 4.0.4 on 2022-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_live_time_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendace_report',
            name='present_time',
            field=models.IntegerField(default=0),
        ),
    ]
