# Generated by Django 4.0.4 on 2022-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_recognize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize',
            name='If_posted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recognize',
            name='Response_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recognize',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
