# Generated by Django 4.0.4 on 2022-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_recognize_if_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('If_posted', models.IntegerField(default=0)),
                ('Response_charge', models.IntegerField(default=0)),
            ],
        ),
    ]
