# Generated by Django 4.0.4 on 2022-05-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_reg_teacher_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('join_code', models.IntegerField()),
            ],
        ),
    ]
