# Generated by Django 4.0.4 on 2022-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_approved_non_approved_alter_course_str_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='s_id',
            field=models.IntegerField(default='10000000'),
        ),
        migrations.AddField(
            model_name='non_approved',
            name='s_id',
            field=models.IntegerField(default='10000000'),
        ),
    ]
