# Generated by Django 4.0.4 on 2022-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student_attendace_report_alter_live_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_str',
            name='time_present',
            field=models.IntegerField(default=0),
        ),
    ]
