# Generated by Django 4.0.4 on 2022-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_present_time_student_attendace_report_time_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendace_report',
            name='time_present',
            field=models.IntegerField(),
        ),
    ]
