# Generated by Django 4.0.4 on 2022-05-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_approved_join_code_alter_course_join_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
