# Generated by Django 4.0.4 on 2022-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='generatec',
            fields=[
                ('len', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
