# Generated by Django 4.0.4 on 2022-05-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student_attendace_report_present_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendace_report',
            old_name='present_time',
            new_name='time_present',
        ),
    ]
