# Generated by Django 4.0.4 on 2022-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='bool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='live',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='live',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='live',
            name='radius',
            field=models.IntegerField(default=0),
        ),
    ]
