# Generated by Django 4.0.4 on 2022-05-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_course_str_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='join_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='join_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='non_approved',
            name='join_code',
            field=models.CharField(max_length=100),
        ),
    ]
