# Generated by Django 4.0.4 on 2022-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_join_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.IntegerField(default=0)),
                ('Course_name', models.CharField(max_length=100)),
            ],
        ),
    ]
