# Generated by Django 4.0.4 on 2022-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_generatec_id_alter_generatec_len'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatec',
            name='id',
        ),
        migrations.AlterField(
            model_name='generatec',
            name='len',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
